markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "奔跑的蚂蚁"
markdown: rdiscount

author: "TaoWang"
atom-baseurl: "http://wangtaox.github.io"
disqus: "wangtaoX"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
